### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by goldbattle** [gobuffalo/velvet#1]
I don't see it documented anyplace, but is it possible add comments to the template?
For example: `{{#comment This text will not be rendered, or shown in the html }}`

**Comment by markbates** [comment]
I don't believe so.

**Comment by goldbattle** [comment]
Thanks

**Comment by markbates** [comment]
@goldbattle I just had a chance to look at this, and yes, comments are supported:

`{{! "this is a comment" }}`

I will add this to the docs.
